{{-
	config(
		materialized='view'
	)
-}}

select
    flag_latest,
    flag_tombstoned,
    dts_effective_from,
    dts_effective_to,
    {{ clean_string('player_id') }} as gsis_player_id,
    {{ clean_integer('season') }} as nfl_season,
    {{ clean_integer('week') }} as nfl_week,
    {{ clean_string('recent_team') }} as nfl_team_code,
    {{ clean_string('season_type') }} as nfl_game_type,
    {{ clean_string('opponent_team') }} as nfl_team_code_opponent,
    {{ clean_integer('completions') }} as total_passing_completions,
    {{ clean_integer('attempts') }} as total_passing_attempts,
    {{ clean_integer('passing_yards') }} as total_passing_yards,
    {{ clean_integer('passing_tds') }} as total_passing_touchdowns,
    {{ clean_integer('interceptions') }} as total_interceptions,
    {{ clean_integer('sacks') }} as total_sacks,
    {{ clean_integer('sack_yards') }} as total_sack_yards,
    {{ clean_integer('sack_fumbles') }} as total_sack_fumbles,
    {{ clean_integer('sack_fumbles_lost') }} as total_sack_fumbles_lost,
    {{ clean_integer('passing_air_yards') }} as total_passing_air_yards,
    {{ clean_integer('passing_yards_after_catch') }} as total_passing_yards_after_catch,
    {{ clean_integer('passing_first_downs') }} as total_passing_first_downs,
    {{ clean_decimal('passing_epa', 16) }} as total_passing_expected_points_added,
    {{ clean_integer('passing_2pt_conversions') }} as total_passing_2pt_conversions,
    {{ clean_decimal('pacr', 16) }} as passing_air_yard_conversion_ratio,
    {{ clean_decimal('dakota', 16) }} as adjusted_epa_plus_cpoe,
    {{ clean_integer('carries') }} as total_carries,
    {{ clean_integer('rushing_yards') }} as total_rushing_yards,
    {{ clean_integer('rushing_tds') }} as total_rushing_touchdowns,
    {{ clean_integer('rushing_fumbles') }} as total_rushing_fumbles,
    {{ clean_integer('rushing_fumbles_lost') }} as total_rushing_fumbles_lost,
    {{ clean_integer('rushing_first_downs') }} as total_rushing_first_downs,
    {{ clean_decimal('rushing_epa', 16) }} as total_rushing_expected_points_added,
    {{ clean_integer('rushing_2pt_conversions') }} as total_rushing_2pt_conversions,
    {{ clean_integer('receptions') }} as total_receptions,
    {{ clean_integer('targets') }} as total_targets,
    {{ clean_integer('receiving_yards') }} as total_receiving_yards,
    {{ clean_integer('receiving_tds') }} as total_receiving_touchdowns,
    {{ clean_integer('receiving_fumbles') }} as total_receiving_fumbles,
    {{ clean_integer('receiving_fumbles_lost') }} as total_receiving_fumbles_lost,
    {{ clean_integer('receiving_air_yards') }} as total_receiving_air_yards,
    {{ clean_integer('receiving_yards_after_catch') }} as total_receiving_yards_after_catch,
    {{ clean_integer('receiving_first_downs') }} as total_receiving_first_downs,
    {{ clean_decimal('receiving_epa', 16) }} as total_receiving_expected_points_added,
    {{ clean_integer('receiving_2pt_conversions') }} as total_receiving_2pt_conversions,
    {{ clean_decimal('racr', 16) }} as receiving_air_yard_conversion_ratio,
    {{ clean_decimal('target_share', 16) }} as total_target_share,
    {{ clean_decimal('air_yards_share', 16) }} as total_air_yard_share,
    {{ clean_decimal('wopr', 16) }} as weighted_opportunity_rating,
    {{ clean_integer('special_teams_tds') }} as total_special_teams_touchdowns,
    {{ clean_decimal('fantasy_points') }} as total_fantasy_points,
    {{ clean_decimal('fantasy_points_ppr') }} as total_fantasy_points_ppr
from
    {{ ref('hist__dim__nflverse__player_stats_offense') }}