{{-
	config(
		materialized='view'
	)
-}}

select
    flag_latest,
    flag_tombstoned,
    dts_effective_from,
    dts_effective_to,
    {{ clean_string('game_id') }} as nfl_game_id,
    {{ clean_integer('play_id') }} as game_play_id,
    {{ clean_integer('order_sequence') }} as game_play_order_sequence,
    {{ clean_integer('season') }} as nfl_season,
    {{ clean_string('posteam') }} as nfl_team_id_possessing,
    {{ clean_string('defteam') }} as nfl_team_id_defending,
    {{ clean_integer('game_seconds_remaining') }} as seconds_remaining_game,
    {{ clean_string('game_half') }} as game_half,
    {{ clean_integer('half_seconds_remaining') }} as seconds_remaining_half,
    {{ clean_integer('qtr') }} as quarter,
    {{ clean_integer('quarter_seconds_remaining') }} as seconds_remaining_quarter,
    {{ clean_string('time') }} as time_on_game_clock,
    {{ clean_bool('quarter_end') }} as flag_quarter_end,
    {{ clean_integer('home_timeouts_remaining') }} as timeouts_remaining_home,
    {{ clean_integer('away_timeouts_remaining') }} as timeouts_remaining_away,
    {{ clean_integer('posteam_score') }} as score_possessing_team,
    {{ clean_integer('defteam_score') }} as score_defending_team,
    {{ clean_integer('posteam_score_post') }} as score_post_play_posessing,
    {{ clean_integer('defteam_score_post') }} as score_post_play_defending,
    {{ clean_integer('drive') }} as game_drive,
    {{ clean_integer('drive_play_id_started') }} as game_play_id_drive_started,
    {{ clean_integer('drive_play_id_ended') }} as game_play_id_drive_ended,
    {{ clean_timestamp('drive_real_start_time', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') }} as dts_drive_started,
    {{ clean_integer('series') }} as game_series,
    {{ clean_bool('series_success') }} as flag_series_success,
    {{ clean_string('series_result') }} as series_result,
    {{ clean_integer('down') }} as series_down,
    {{ clean_integer('ydstogo') }} as series_yards_to_go,
    {{ clean_bool('goal_to_go') }} as flag_goal_to_go,
    {{ clean_string('side_of_field') }} as nlf_team_id_side_of_field,
    split_part({{ clean_string('yrdln') }}, ' ', 2)::int as side_of_field_yard_line,
    {{ clean_integer('yardline_100') }} as yards_from_opponent_endzone,
    {{ clean_integer('ydsnet') }} as drive_total_yards,
    {{ clean_string('play_type') }} as play_type,
    {{ clean_bool('sp') }} as flag_scoring_play,
    {{ clean_string('"desc"') }} as play_description,
    {{ clean_integer('yards_gained') }} as play_yards_gained,
    {{ clean_string('passer_player_id') }} as gsis_player_id_passer,
    {{ clean_bool('shotgun') }} as flag_shotgun_formation,
    {{ clean_bool('no_huddle') }} as flag_no_huddle,
    {{ clean_bool('qb_dropback') }} as flag_quarterback_dropback,
    {{ clean_bool('qb_spike') }} as flag_quarterback_spike,
    {{ clean_bool('qb_scramble') }} as flag_quarterback_scramble,
    {{ clean_bool('qb_hit') }} as flag_quarterback_hit,
    {{ clean_string('qb_hit_1_player_id') }} as gsis_player_id_quarterback_hitter_1,
    {{ clean_string('qb_hit_2_player_id') }} as gsis_player_id_quarterback_hitter_2,
    {{ clean_bool('sack') }} as flag_quarterback_sacked,
    {{ clean_string('sack_player_id') }} as gsis_player_id_quarterback_sacker,
    {{ clean_string('half_sack_1_player_id') }} as gsis_player_id_quarterback_half_sacker_1,
    {{ clean_string('half_sack_2_player_id') }} as gsis_player_id_quarterback_half_sacker_2,
    {{ clean_bool('complete_pass') }} as flag_complete_pass,
    {{ clean_bool('incomplete_pass') }} as flag_incomplete_pass,
    {{ clean_decimal('cp', 16) }} as completed_pass_probability,
    {{ clean_decimal('cpoe', 16) }} as completion_percentage_over_expected,
    {{ clean_string('pass_location') }} as pass_location,
    {{ clean_integer('air_yards') }} as air_yards,
    {{ clean_string('receiver_player_id') }} as gsis_player_id_receiver,
    {{ clean_integer('yards_after_catch') }} as yards_after_catch,
    {{ clean_bool('interception') }} as flag_pass_intercepted,
    {{ clean_string('interception_player_id') }} as gsis_player_id_interceptor,
    {{ clean_string('rusher_player_id') }} as gsis_player_id_rusher,
    {{ clean_string('run_location') }} as run_location,
    {{ clean_string('run_gap') }} as run_gap,
    {{ clean_bool('tackled_for_loss') }} as flag_tackled_for_loss,
    {{ clean_bool('touchdown') }} as flag_touchdown,
    {{ clean_string('td_team') }} as nfl_team_id_touchdown,
    {{ clean_string('td_player_id') }} as gsis_player_id_touchdown_scorer,
    {{ clean_string('third_down_converted') }} as flag_third_down_converted,
    {{ clean_bool('third_down_failed') }} as flag_third_down_failed,
    {{ clean_bool('fourth_down_converted') }} as flag_fourth_down_converted,
    {{ clean_bool('fourth_down_failed') }} as flag_fourth_down_failed,
    {{ clean_bool('extra_point_attempt') }} as flag_extra_point_attempt,
    {{ clean_string('extra_point_result') }} as extra_point_result,
    {{ clean_bool('field_goal_attempt') }} as flag_field_goal_attempt,
    {{ clean_string('field_goal_result') }} as field_goal_result,
    {{ clean_bool('two_point_attempt') }} as flag_two_point_conversion_attempt,
    {{ clean_string('two_point_conv_result') }} as two_point_conversion_result,
    {{ clean_bool('replay_or_challenge') }} as flag_play_replayed_or_challenged,
    {{ clean_string('replay_or_challenge_result') }} as replay_or_challenge_result,
    {{ clean_bool('kickoff_attempt') }} as flag_kickoff_attempt,
    {{ clean_bool('kickoff_out_of_bounds') }} as flag_kickoff_out_of_bounds,
    {{ clean_bool('kickoff_downed') }} as flag_kickoff_downed,
    {{ clean_bool('kickoff_fair_catch') }} as flag_kickoff_fair_catch,
    {{ clean_string('kicker_player_id') }} as gsis_player_id_kicker,
    {{ clean_string('kickoff_returner_player_id') }} as gsis_player_id_kick_returner,
    {{ clean_bool('punt_attempt') }} as flag_punt_attempt,
    {{ clean_string('blocked_player_id') }} as gsis_player_id_punt_blocker,
    {{ clean_bool('punt_blocked') }} as flag_punt_blocked,
    {{ clean_bool('punt_out_of_bounds') }} as flag_punt_out_of_bounds,
    {{ clean_bool('punt_downed') }} as flag_punt_downed,
    {{ clean_bool('punt_fair_catch') }} as flag_punt_fair_catch,
    {{ clean_string('punter_player_id') }} as gsis_player_id_punter,
    {{ clean_string('punt_returner_player_id') }} as gsis_player_id_punt_returner,
    {{ clean_integer('kick_distance') }} as kick_distance,
    {{ clean_string('return_team') }} as nfl_team_id_return_team,
    {{ clean_integer('return_yards') }} as return_yards,
    {{ clean_bool('touchback') }} as flag_touchback,
    {{ clean_bool('aborted_play') }} as flag_aborted_play,
    {{ clean_bool('timeout') }} as flag_timeout,
    {{ clean_string('timeout_team') }} as nfl_team_id_timeout,
    {{ clean_bool('penalty') }} as flag_penalty,
    {{ clean_bool('safety') }} as flag_safety,
    {{ clean_string('safety_player_id') }} as gsis_player_id_safety,
    {{ clean_decimal('no_score_prob', 16) }} as no_score_probability,
    {{ clean_decimal('fg_prob', 16) }} as field_goal_probability,
    {{ clean_decimal('td_prob', 16) }} as touchdown_probability,
    {{ clean_decimal('extra_point_prob', 16) }} as extra_point_probability,
    {{ clean_decimal('two_point_conversion_prob', 16) }} as two_point_conversion_prob,
    {{ clean_decimal('safety_prob', 16) }} as safety_probability,
    {{ clean_decimal('opp_fg_prob', 16) }} as opponent_field_goal_probability,
    {{ clean_decimal('opp_safety_prob', 16) }} as opponent_safety_probability,
    {{ clean_decimal('opp_td_prob', 16) }} as opponent_touchdown_probability,
    {{ clean_decimal('ep', 16) }} as expected_points_from_play,
    {{ clean_decimal('epa', 16) }} as expected_points_added_from_play,
    {{ clean_decimal('total_home_epa', 16) }} as total_home_expected_points_added,
    {{ clean_decimal('total_away_epa', 16) }} as total_away_expected_points_added,
    {{ clean_decimal('total_home_rush_epa', 16) }} as total_home_rush_expected_points_added,
    {{ clean_decimal('total_away_rush_epa', 16) }} as total_away_rush_expected_points_added,
    {{ clean_decimal('total_home_pass_epa', 16) }} as total_home_pass_expected_points_added,
    {{ clean_decimal('total_away_pass_epa', 16) }} as total_away_pass_expected_points_added,
    {{ clean_decimal('air_epa', 16) }} as air_yard_expected_points_added,
    {{ clean_decimal('yac_epa', 16) }} as yards_after_catch_expected_points_added,
    {{ clean_decimal('comp_air_epa', 16) }} as completion_air_yard_expected_points_added,
    {{ clean_decimal('comp_yac_epa', 16) }} as completion_yards_after_contact_expected_points_added,
    {{ clean_decimal('total_home_comp_air_epa', 16) }} as total_home_comp_air_yard_expected_points_added,
    {{ clean_decimal('total_away_comp_air_epa', 16) }} as total_away_comp_air_yard_expected_points_added,
    {{ clean_decimal('total_home_comp_yac_epa', 16) }} as total_home_comp_yards_after_contact_expected_points_added,
    {{ clean_decimal('total_away_comp_yac_epa', 16) }} as total_away_comp_yards_after_contact_expected_points_added,
    {{ clean_decimal('total_home_raw_air_epa', 16) }} as total_home_raw_air_yard_expected_points_added,
    {{ clean_decimal('total_away_raw_air_epa', 16) }} as total_away_raw_air_yard_expected_points_added,
    {{ clean_decimal('total_home_raw_yac_epa', 16) }} as total_home_raw_yards_after_contact_expected_points_added,
    {{ clean_decimal('total_away_raw_yac_epa', 16) }} as total_away_raw_yards_after_contact_expected_points_added,
    {{ clean_decimal('wp', 16) }} as win_percentage_before_play,
    {{ clean_decimal('def_wp', 16) }} as def_win_percentage_before_play,
    {{ clean_decimal('home_wp', 16) }} as home_win_percentage_before_play,
    {{ clean_decimal('away_wp', 16) }} as away_win_percentage_before_play,
    {{ clean_decimal('wpa', 16) }} as win_percentage_added_by_play,
    {{ clean_decimal('home_wp_post', 16) }} as home_win_percentage_after_play,
    {{ clean_decimal('away_wp_post', 16) }} as away_win_percentage_after_play,
    {{ clean_decimal('total_home_rush_wpa', 16) }} as total_home_rush_win_percentage_added_by_play,
    {{ clean_decimal('total_away_rush_wpa', 16) }} as total_away_rush_win_percentage_added_by_play,
    {{ clean_decimal('total_home_pass_wpa', 16) }} as total_home_pass_win_percentage_added_by_play,
    {{ clean_decimal('total_away_pass_wpa', 16) }} as total_away_pass_win_percentage_added_by_play,
    {{ clean_decimal('air_wpa', 16) }} as air_yard_win_percentage_added_by_play,
    {{ clean_decimal('yac_wpa', 16) }} as yars_after_contact_win_percentage_added_by_play,
    {{ clean_decimal('comp_air_wpa', 16) }} as completion_air_yard_win_percentage_added_by_play,
    {{ clean_decimal('comp_yac_wpa', 16) }} as completion_yards_after_contact_win_percentage_added_by_play,
    {{ clean_decimal('total_home_comp_air_wpa', 16) }} as total_home_completion_air_yard_win_percentage_added_by_play,
    {{ clean_decimal('total_away_comp_air_wpa', 16) }} as total_away_completion_air_yard_win_percentage_added_by_play,
    {{ clean_decimal('total_home_comp_yac_wpa', 16) }} as total_home_completion_yards_after_contact_win_percentage_added_by_play,
    {{ clean_decimal('total_away_comp_yac_wpa', 16) }} as total_away_completion_yards_after_contact_win_percentage_added_by_play,
    {{ clean_decimal('total_home_raw_air_wpa', 16) }} as total_home_raw_air_yard_win_percentage_added_by_play,
    {{ clean_decimal('total_away_raw_air_wpa', 16) }} as total_away_raw_air_yard_win_percentage_added_by_play,
    {{ clean_decimal('total_home_raw_yac_wpa', 16) }} as total_home_raw_yards_after_contact_win_percentage_added_by_play,
    {{ clean_decimal('total_away_raw_yac_wpa', 16) }} as total_away_raw_yards_after_contact_win_percentage_added_by_play,
    {{ clean_bool('solo_tackle') }} as flag_solo_tackle,
    {{ clean_bool('assist_tackle') }} as flag_assist_tackle,
    {{ clean_string('pass_defense_1_player_id') }} as gsis_player_id_pass_defender_1,
    {{ clean_string('pass_defense_2_player_id') }} as gsis_player_id_pass_defender_2,
    {{ clean_string('tackle_for_loss_1_player_id') }} as gsis_player_id_loss_tackler_1,
    {{ clean_string('tackle_for_loss_2_player_id') }} as gsis_player_id_loss_tackler_2,
    {{ clean_string('solo_tackle_1_team') }} as nfl_team_id_solo_tackler_1,
    {{ clean_string('solo_tackle_1_player_id') }} as gsis_player_id_solo_tackler_1,
    {{ clean_string('solo_tackle_2_team') }} as nfl_team_id_solo_tackler_2,
    {{ clean_string('solo_tackle_2_player_id') }} as gsis_player_id_solo_tackler_2,
    {{ clean_string('assist_tackle_1_team') }} as nfl_team_id_assist_tackler_1,
    {{ clean_string('assist_tackle_1_player_id') }} as gsis_player_id_assist_tackler_1,
    {{ clean_string('assist_tackle_2_team') }} as nfl_team_id_assist_tackler_2,
    {{ clean_string('assist_tackle_2_player_id') }} as gsis_player_id_assist_tackler_2,
    {{ clean_string('assist_tackle_3_team') }} as nfl_team_id_assist_tackler_3,
    {{ clean_string('assist_tackle_3_player_id') }} as gsis_player_id_assist_tackler_3,
    {{ clean_string('assist_tackle_4_team') }} as nfl_team_id_assist_tackler_4,
    {{ clean_string('assist_tackle_4_player_id') }} as gsis_player_id_assist_tackler_4,
    {{ clean_string('tackle_with_assist') }} as flag_tackle_with_assist,
    {{ clean_string('tackle_with_assist_1_team') }} as nfl_team_id_tackle_with_assist_tackler_1,
    {{ clean_string('tackle_with_assist_1_player_id') }} as gsis_player_id_tackle_with_assist_tackler_1,
    {{ clean_string('tackle_with_assist_2_team') }} as nfl_team_id_tackle_with_assist_tackler_2,
    {{ clean_string('tackle_with_assist_2_player_id') }} as gsis_player_id_tackle_with_assist_tackler_2,
    {{ clean_bool('fumble') }} as flag_fumble,
    {{ clean_bool('fumble_lost') }} as flag_fumble_lost,
    {{ clean_bool('fumble_forced') }} as flag_fumble_forced,
    {{ clean_bool('fumble_not_forced') }} as flag_fumble_not_forced,
    {{ clean_bool('fumble_out_of_bounds') }} as flag_fumble_out_of_bounds,
    {{ clean_string('fumbled_1_player_id') }} as gsis_player_id_fumbler_1,
    {{ clean_string('fumbled_1_team') }} as nfl_team_id_fumbler_1,
    {{ clean_string('fumbled_2_player_id') }} as gsis_player_id_fumbler_2,
    {{ clean_string('fumbled_2_team') }} as nfl_team_id_fumbler_2,
    {{ clean_string('fumble_recovery_1_player_id') }} as gsis_player_id_fumble_recoverer_1,
    {{ clean_string('fumble_recovery_1_team') }} as nfl_team_id_fumble_recoverer_1,
    {{ clean_string('fumble_recovery_1_yards') }} as fumble_recoverer_1_yards,
    {{ clean_string('fumble_recovery_2_player_id') }} as gsis_player_id_fumble_recoverer_2,
    {{ clean_string('fumble_recovery_2_team') }} as nfl_team_id_fumble_recoverer_2,
    {{ clean_string('fumble_recovery_2_yards') }} as fumble_recoverer_2_yards,
    {{ clean_string('forced_fumble_player_1_team') }} as nfl_team_id_fumble_forcer_1,
    {{ clean_string('forced_fumble_player_1_player_id') }} as gsis_player_id_fumble_forcer_1,
    {{ clean_string('forced_fumble_player_2_team') }} as nfl_team_id_fumble_forcer_2,
    {{ clean_string('forced_fumble_player_2_player_id') }} as gsis_player_id_fumble_forcer_2,
    {{ clean_bool('lateral_reception') }} as flag_lateral_reception,
    {{ clean_string('lateral_receiver_player_id') }} as gsis_player_id_lateral_receiver,
    {{ clean_bool('lateral_rush') }} as flag_lateral_rush,
    {{ clean_string('lateral_rusher_player_id') }} as gsis_player_id_lateral_rusher,
    {{ clean_bool('lateral_return') }} as flag_lateral_return,
    {{ clean_bool('lateral_recovery') }} as flag_lateral_recovery,
    {{ clean_string('lateral_sack_player_id') }} as gsis_player_id_lateral_sacker,
    {{ clean_string('lateral_interception_player_id') }} as gsis_player_id_lateral_interceptor,
    {{ clean_string('lateral_punt_returner_player_id') }} as gsis_player_id_lateral_punt_returner,
    {{ clean_string('lateral_kickoff_returner_player_id') }} as gsis_player_id_lateral_kickoff_returner,
    {{ clean_string('own_kickoff_recovery_player_id') }} as gsis_player_id_own_kickoff_returner,
    {{ clean_bool('own_kickoff_recovery') }} as flag_own_kickoff_recovery,
    {{ clean_bool('own_kickoff_recovery_td') }} as flag_own_kickoff_recovery_touchdown,
    {{ clean_bool('defensive_two_point_attempt') }} as flag_defensive_two_point_conversion_attempt,
    {{ clean_bool('defensive_two_point_conv') }} as flag_defensive_two_point_conversion_successful,
    {{ clean_bool('defensive_extra_point_attempt') }} as flag_defensive_extra_point_attempt,
    {{ clean_bool('defensive_extra_point_conv') }} as flag_defensive_extra_point_successful
from
    {{ ref('hist__dim__nflverse__play_by_play') }}